### ISSUE TITLE
getData using 'series' as filter does not return expected data series

### ISSUE THREAD

**Issue by nitschkematthew** [AIMS/data-platform-r#1]
Thank you for making this package!

Here is a minimal reprex for the issue:

```
library("aimsdataplatform")
library("dplyr")
```
This returns a series_name of "Orpheus Island Relay Pole 2 Water Temperature @7.3m"
```
query <- getFilterValues('10.25845/5c09bf93f315d', 'series') %>%
filter(series_id == 14838)
```
The result of the following `getData` call:
```
result <- getData('10.25845/5c09bf93f315d', apiKey = MY_API_KEY, filters = list('series' = query$series_id, 'from-date' = '2018-08-21', 'thru-date' = '2020-02-21'))
```
is
```
[1] "Cite this data as: Australian Institute of Marine Science (AIMS). 2009, Australian Institute of Marine Science Automatic Weather Stations, https://doi.org/10.25845/5c09bf93f315d, accessed 21 February 2020.  Time period: 2018-08-21 to 2020-02-21.  Series: Hardy Reef Platform Humidity."
[1] "Result count: "
```
and not the data from Orpheus island as expected.

Thank you!

```

**Comment by jlsheehan** [comment]
Hi Matthew,

Did you get an API key from [here](https://aims.github.io/data-platform/key-request)?

**Comment by nitschkematthew** [comment]
Thanks @jlsheehan. Yes in the reprex above I am using my own API key.

**Comment by jlsheehan** [comment]
Hi @nitschkematthew ,

Its difficult for me to test right now, but I think that the issue is there's no data at the time period you have specified.

If I extend the query back to 2016 then I get some data, so making 'from-date' = '2016-08-21' and keeping the other values the same.  Perhaps if you did a chart of a larger time period you could find where the gaps are and pick a time period thats useful.

I'll make another issue for us to improve the error messages so you get some helpful information back when there's no data found.

Jeff S

**Comment by nitschkematthew** [comment]
Thanks @jlsheehan. Yes, this solves the issue. When a call is made to a series with a filter for a time period that is without data, it seems to come back with `Hardy Reef Platform Humidity` as the default.

Issue closed!
